### ISSUE TITLE
update URLs for RDF serializations

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_ngl#1]
Includes updating `dct:hasFormat` values in triples files and updating links to serializations at top of doc.

@gerontakos please let me know once you have:
1. renamed repo if renaming
2. copied-over data from [uwlswd_vocabs](https://github.com/uwlib-cams/uwlswd_vocabs) (without deleting it from that repo, until DOI reconfiguration is complete)

Following this, I'll set up GitHub Pages to publish content from the main branch's root directory (as with MARC 006, 007, and 008 vocabs), confirm new file URLs, and update these where they occur in the data.

**Comment by briesenberg07** [comment]
Thank you @gerontakos --  

**Please see my proposal on [modelling for dct:hasFormat](https://github.com/uwlib-cams/uwlswd/discussions/14) and share any feedback--I think we may have different ideas about this (?)** and want to confirm usage of the property. I created the discussion in [uwlswd](https://github.com/uwlib-cams/uwlswd) because it applies, I believe, to all datasets and vocabs.

If I understand correctly, *new* RDF serializations will be created from the MARC/XML to-be-loaded, so no any changes made to RDF files (.json, .nt, .rdf, .ttl) currently in repository would be overwritten. I will wait until MARC/XML-to-RDF and MARC/XML-to-HTML+RDFa are complete to update URL values for `dct:hasFormat` triples.  

I see per your email that you will rename newspaperGenreList to newspaper_genre_list per [UWLSWD file-naming conventions](https://github.com/uwlib-cams/uwlswd/wiki/naming-conventions#dataset-and-vocabulary-file-names).

Thank you!  
CC @E-Fl0

**Comment by briesenberg07** [comment]
Hey @gerontakos also fix triple:
```
<> dct:hasFormat <https://uwlib-cams.github.io/uwlswd_ngl/newspaper_genre_list .
```

**Comment by gerontakos** [comment]
Above url removed. All hasFormat values repaired in marcxml2rdfxml.xsl
