### ISSUE TITLE
incorrect triple in newspaper_genre_list.nt?

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_ngl#10]
Triple\*:

```
<https://doi.org/10.6069/uwlib.55.d.5> <http://purl.org/dc/terms/hasFormat> <https://uwlib-cams.github.io/uwlswd_vocabs/newspaper_genre_list> .
```
\*[View in repo](https://github.com/uwlib-cams/uwlswd_vocabs/blob/9cd026870e51bc71548a5fb50240bba1a5bc865d/newspaper_genre_list.nt#L132)

Seems we don't need this triple?  
Six other `dct:hasFormat` triples exist, with objects
- .xml (MARC21)
- .rdf
- .nt
- [HTML page](https://www.lib.washington.edu/gmm/collections/mcnews/ngl) in Libraries public pages
- .json
- .ttl

**Comment by gerontakos** [comment]
It's done

**Comment by gerontakos** [comment]
closed in error
